cmds = [
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:1",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:2",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:3",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:4",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:5",
        # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:6",
        # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:7",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:1",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:2",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:3",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:4",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:5",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:6",
        # # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:7",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:2-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:2",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:3-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:3",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:4-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:4",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:1-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:1",
        "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:5-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:5",
        # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:6-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:6",
        # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:7-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:7",
]


# cmds = [
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=1 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work//04.02_13:59-tagspec-ctx-select:1/HybridTrainer-best-epoch-76.ptr'           -n load_constituency_parsing_model-ctx-sfnt:1",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=2 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:2/HybridTrainer-best-epoch-67.ptr'  -n load_constituency_parsing_model-ctx-sfnt:2",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=3 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:3/HybridTrainer-best-epoch-76.ptr'  -n load_constituency_parsing_model-ctx-sfnt:3",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=4 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:4/HybridTrainer-best-epoch-74.ptr'  -n load_constituency_parsing_model-ctx-sfnt:4",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=5 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:5/HybridTrainer-best-epoch-85.ptr'  -n load_constituency_parsing_model-ctx-sfnt:5",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=6 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:6/HybridTrainer-best-epoch-91.ptr'  -n load_constituency_parsing_model-ctx-sfnt:6",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=7 gen_model=ctx resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:7/HybridTrainer-best-epoch-94.ptr'  -n load_constituency_parsing_model-ctx-sfnt:7",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=1 gen_model=rnd'           -n load_constituency_parsing_model-rnd-sfnt:1",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=2 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:2",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=3 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:3",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=4 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:4",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=5 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:5",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=6 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:6",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=7 gen_model=rnd'  -n load_constituency_parsing_model-rnd-sfnt:7",
# ]


# cmds = [
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=1 resume_ctx=/disk/ostrom/s1884529/zfhu/work//04.02_13:59-tagspec-ctx-select:1/HybridTrainer-best-epoch-76.ptr'           -n cherry_pick-sfnt:1",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=2 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:2/HybridTrainer-best-epoch-67.ptr'  -n cherry_pick-sfnt:2",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=3 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:3/HybridTrainer-best-epoch-76.ptr'  -n cherry_pick-sfnt:3",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=4 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:4/HybridTrainer-best-epoch-74.ptr'  -n cherry_pick-sfnt:4",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=5 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:5/HybridTrainer-best-epoch-85.ptr'  -n cherry_pick-sfnt:5",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=6 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:6/HybridTrainer-best-epoch-91.ptr'  -n cherry_pick-sfnt:6",
#         "python {}/run.py -g {} -e 'resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr use_pos=True select_first_n_tag=7 resume_ctx=/disk/ostrom/s1884529/zfhu/work/03.01_08:51-tagspec-avoid-use_pos-select:7/HybridTrainer-best-epoch-94.ptr'  -n cherry_pick-sfnt:7",
# ]

# cmds = [
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:1-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-1",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:2-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-2",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:3-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-3",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:4-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-4",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:5-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-5",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:6-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-6",
#         "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:7-03.02_18:19/export_test.conll' -n load_pretrained_allennlp_model-test-rnd-7",
# ]

# cmds = [
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:1",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:2",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:3",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:4",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:5",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:6",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_08:51' -n build_allennlp_attacker-tagspec-use_pos-select:7",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:1",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:2",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:3",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:4",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:5",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:6",
#         # "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_15:18' -n build_allennlp_attacker-tagspec-no_pos-select:7",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:2-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:2",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:3-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:3",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:4-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:4",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:1-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:1",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:5-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:5",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:6-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:6",
#         "python {}/run.py -g {} -e 'attack_file_dir=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:7-03.02_18:19' -n build_allennlp_attacker-tagspec-rnd-use_pos-select:7",
# ]

# cmds = [
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:1",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:2",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:3",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:4",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:5",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:6",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_08:51/export_test.conll' -n attack_with_bert-tagspec-ctx-use_pos-select:7",

#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:1-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:1",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:2-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:2",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:3-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:3",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:4-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:4",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:5-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:5",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:6-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:6",
#         # "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_ctx_aoivd/tagspec-avoid-use_pos-select:7-03.01_15:18/export_test.conll' -n attack_with_bert-tagspec-no_pos-select:7",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:2-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:1",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:3-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:2",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:4-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:3",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:1-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:4",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:5-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:5",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:6-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:6",
#         "python {}/run.py -g {} -e 'attack_file=$ROOT/v1zhu2/work/_tagspec_rnd_select/tagspec-rnd-select:7-03.02_18:19/export_test.conll' -n attack_with_bert-tagspec-rnd-select:7",
# ]


__cmds = [
# evaluation_on_allennlp_cmds = [
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:1-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-1   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:2-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-2   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:3-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-3   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:4-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-4   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:5-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-5   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:6-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-6   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:7-03.01_15:18/export_test.conll' -n load_pretrained_allennlp_model-no_pos-7   ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:1-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-1 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:2-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-2 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:3-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-3 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:4-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-4 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:5-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-5 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:6-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-6 ",
        # "python {}/run.py -g {} -e 'infer_data=$ROOT/v1zhu2/work/tagspec-avoid-use_pos-select:7-03.01_08:51/export_test.conll' -n load_pretrained_allennlp_model-standard-7 ",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=1 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:1",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=2 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:2",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=3 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:3",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=4 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:4",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=5 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:5",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=6 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:6",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=7 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-rnd-no_pos-select:7",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=1 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:1",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=2 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:2",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=3 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:3",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=4 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:4",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=5 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:5",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=6 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:6",
        "python {}/run.py -g {} -e 'gen_model=rnd select_first_n_tag=7 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-rnd-select:7",

]

train_tagspec_cmds = [
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=1 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:1",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=2 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:2",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=3 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:3",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=4 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:4",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=5 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:5",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=6 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:6",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=7 use_pos=False resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:32-train_a_parser-no_pos/trainer-best-epoch-126.ptr' -n tagspec-avoid-use_pos-select:7",
]


__cmds = [
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=1 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:1",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=2 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:2",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=3 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:3",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=4 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:4",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=5 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:5",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=6 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:6",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'gen_model=ctx select_first_n_tag=7 use_pos=True resume_parser=/disk/ostrom/s1884529/zfhu/work/02.28_18:28-train_a_parser/trainer-best-epoch-105.ptr' -n tagspec-avoid-use_pos-select:7",

]


___cmds = [
        "python {}/run.py -m gateway.py -g {} -c basic -e 'ent_penalty=10 obf_until_tagset=3' -n tagspec-obf_until_tagset:3-ent:10",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'ent_penalty=10 obf_until_tagset=4' -n tagspec-obf_until_tagset:4-ent:10",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'ent_penalty=10 obf_until_tagset=5' -n tagspec-obf_until_tagset:5-ent:10",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'ent_penalty=10 obf_until_tagset=6' -n tagspec-obf_until_tagset:6-ent:10",
        "python {}/run.py -m gateway.py -g {} -c basic -e 'ent_penalty=10 obf_until_tagset=7' -n tagspec-obf_until_tagset:7-ent:10",
]

__cmds = [
        "python {}/run.py -m gateway.py -g {} -c basic -e ent_penalty=1.0 -n two_stage_no_copy-ent:1.0",
        "python {}/run.py -m gateway.py -g {} -c basic -e ent_penalty=5.0 -n two_stage_no_copy-ent:5.0",
        "python {}/run.py -m gateway.py -g {} -c basic -e ent_penalty=10.0 -n two_stage_no_copy-ent:10.0",
        "python {}/run.py -m gateway.py -g {} -c basic -e ent_penalty=20.0 -n two_stage_no_copy-ent:20.0"
]

_cmds = [
  #  "unk_rate=0.0 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.0",
  #  "unk_rate=0.1 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.1",
  #  "unk_rate=0.2 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.2",
  #  "unk_rate=0.3 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.3",
  #  "unk_rate=0.4 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.4",
  #  "unk_rate=0.5 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.5",
  #  "unk_rate=0.6 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.6",
  #  "unk_rate=0.7 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.7",
  #  "unk_rate=0.8 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.8",
  #  "unk_rate=0.9 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-0.9",
  #  "unk_rate=1.0 privacy_term='' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-all-1.0",
  #  "unk_rate=0.0 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.0",
  #  "unk_rate=0.1 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.1",
  #  "unk_rate=0.2 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.2",
  #  "unk_rate=0.3 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.3",
  #  "unk_rate=0.4 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.4",
  #  "unk_rate=0.5 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.5",
  #  "unk_rate=0.6 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.6",
  #  "unk_rate=0.7 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.7",
  #  "unk_rate=0.8 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.8",
  #  "unk_rate=0.9 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-0.9",
  #  "unk_rate=1.0 privacy_term='NN' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NN-1.0",
  #  "unk_rate=0.0 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.0",
  #  "unk_rate=0.1 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.1",
  #  "unk_rate=0.2 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.2",
  #  "unk_rate=0.3 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.3",
  #  "unk_rate=0.4 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.4",
  #  "unk_rate=0.5 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.5",
  #  "unk_rate=0.6 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.6",
  #  "unk_rate=0.7 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.7",
  #  "unk_rate=0.8 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.8",
  #  "unk_rate=0.9 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-0.9",
  #  "unk_rate=1.0 privacy_term='NNP' gen_model='AlltagRandomGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n random_gen-NNP-1.0",
  #  "unk_rate=0.0 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.0",
  #  "unk_rate=0.1 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.1",
  #  "unk_rate=0.2 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.2",
  #  "unk_rate=0.3 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.3",
  #  "unk_rate=0.4 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.4",
  #  "unk_rate=0.5 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.5",
  #  "unk_rate=0.6 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.6",
  #  "unk_rate=0.7 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.7",
  #  "unk_rate=0.8 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.8",
  #  "unk_rate=0.9 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-0.9",
  #  "unk_rate=1.0 privacy_term='' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-all-1.0",
  #  "unk_rate=0.0 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.0",
  #  "unk_rate=0.1 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.1",
  #  "unk_rate=0.2 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.2",
  #  "unk_rate=0.3 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.3",
  #  "unk_rate=0.4 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.4",
  #  "unk_rate=0.5 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.5",
  #  "unk_rate=0.6 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.6",
  #  "unk_rate=0.7 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.7",
  #  "unk_rate=0.8 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.8",
  #  "unk_rate=0.9 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-0.9",
  #  "unk_rate=1.0 privacy_term='NN' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NN-1.0",
  #  "unk_rate=0.0 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.0",
  #  "unk_rate=0.1 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.1",
  #  "unk_rate=0.2 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.2",
  #  "unk_rate=0.3 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.3",
  #  "unk_rate=0.4 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.4",
  #  "unk_rate=0.5 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.5",
  #  "unk_rate=0.6 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.6",
  #  "unk_rate=0.7 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.7",
  #  "unk_rate=0.8 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.8",
  #  "unk_rate=0.9 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-0.9",
  #  "unk_rate=1.0 privacy_term='NNP' gen_model='UnkGenerator' ~/Project/Homomorphic-Obfuscation/run.py -c config.unkgen -g {} -n unk_gen-NNP-1.0",
    "cpy_penalty=0.0 privacy_term='NNP' obf_term='NNP' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:NNP_pri:NNP:0.0",

    "cpy_penalty=0.0 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.0",
    "cpy_penalty=0.1 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.1",
    "cpy_penalty=0.2 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.2",
    "cpy_penalty=0.3 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.3",
    "cpy_penalty=0.4 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.4",
    "cpy_penalty=0.5 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.5",
    "cpy_penalty=0.6 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.6",
    "cpy_penalty=0.7 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.7",
    "cpy_penalty=0.8 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.8",
    "cpy_penalty=0.9 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:0.9",
    "cpy_penalty=1.0 privacy_term='all' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:all_cpy:1.0",
 
    "cpy_penalty=0.0 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.0",
    "cpy_penalty=0.1 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.1",
    "cpy_penalty=0.2 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.2",
    "cpy_penalty=0.3 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.3",
    "cpy_penalty=0.4 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.4",
    "cpy_penalty=0.5 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.5",
    "cpy_penalty=0.6 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.6",
    "cpy_penalty=0.7 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.7",
    "cpy_penalty=0.8 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.8",
    "cpy_penalty=0.9 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:0.9",
    "cpy_penalty=1.0 privacy_term='NNP' obf_term='all' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_obf:all_pri:NNP:1.0",

 #   "cpy_penalty=0.0 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.0",
 #   "cpy_penalty=0.1 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.1",
 #   "cpy_penalty=0.2 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.2",
 #   "cpy_penalty=0.3 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.3",
 #   "cpy_penalty=0.4 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.4",
 #   "cpy_penalty=0.5 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.5",
 #   "cpy_penalty=0.6 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.6",
 #   "cpy_penalty=0.7 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.7",
 #   "cpy_penalty=0.8 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.8",
 #   "cpy_penalty=0.9 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-0.9",
 #   "cpy_penalty=1.0 privacy_term='NN' ~/Project/Homomorphic-Obfuscation/run.py -c config.non_gan -g {} -n seperated_gen-NN-1.0",
 
]
