cmds = [
        "cpy_penalty=0.0 privacy_term='NNP' obf_term='NNP' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:NNP_pri:NNP:0.0",
        "cpy_penalty=0.0 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.0",
        "cpy_penalty=0.1 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.1",
        "cpy_penalty=0.2 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.2",
        "cpy_penalty=0.3 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.3",
        "cpy_penalty=0.4 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.4",
        "cpy_penalty=0.5 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.5",
        "cpy_penalty=0.6 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.6",
        "cpy_penalty=0.7 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.7",
        "cpy_penalty=0.8 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.8",
        "cpy_penalty=0.9 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:0.9",
        "cpy_penalty=1.0 privacy_term='NNP' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:NNP:1.0",
        "cpy_penalty=0.0 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.0",
        "cpy_penalty=0.1 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.1",
        "cpy_penalty=0.2 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.2",
        "cpy_penalty=0.3 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.3",
        "cpy_penalty=0.4 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.4",
        "cpy_penalty=0.5 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.5",
        "cpy_penalty=0.6 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.6",
        "cpy_penalty=0.7 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.7",
        "cpy_penalty=0.8 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.8",
        "cpy_penalty=0.9 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:0.9",
        "cpy_penalty=1.0 privacy_term='all' obf_term='all' ~/Project/HO_separate/run.py -c config.non_gan -g {} -n separated_obf:all_pri:all_cpy:1.0",
        ]
